### ISSUE TITLE
Implement  Operator and controllers as distinct entities with the operator-controller model

### ISSUE THREAD

**Issue by Prashanth684** [outrigger-project/multiarch-tuning-operator#12]
Currently the operator is implemented just as a p-o-c style controller to validate the functionality of adding node affinities on scheduling gated pods. But this is actually just the pod placement controller. We need the operator to manage various controllers such as:

- PodPlacement controller (which is built in to the operator today)
- PodPlacementConfig controller - managing and reconciling the config CR
-  Webhook controller - managing the webhook deployments

Other potential controllers to implement:
-  ICSP/IDMS controller - controller to reconcile and store/update ICSP/IDMS config
-  ImageRegistryConfig controller - update registry configuration and update policies.json

In addition to this, the PodPlacementController should run as an active-standby deployment using leader election. The webhook will be implemented as a replicaset (3 replicas ideally)  to intercept pods and gate them as per config.

This would involve the operator/controller each having their own deployment specs with command line options for each controller to be associated with the respective deployments

- Code would have to be restructured to have an operator package and a package for each controller
- Have deployment yamls for the operator and each controller

**Comment by aleskandro** [comment]
I think we can close this as #21 finalized this work. #23 will be a follow-up regarding the definition of a fine-grained FSM, also helpful for the ordered uninstallation.
