### ISSUE TITLE
Skip static checks when changing non-meaningful files

### ISSUE THREAD

**Issue by Prashanth684** [outrigger-project/multiarch-tuning-operator#14]
currently, we run the pre-merge checks in https://github.com/openshift/release/blob/master/ci-operator/config/openshift/multiarch-manager-operator/openshift-multiarch-manager-operator-main.yaml#L30-L62 for each PR, regardless of which files are being changed.

We can restrict each test to execute only when needed by looking at the changed files and excluding some via regexp.

See `skip_if_only_changed` https://steps.ci.openshift.org/ci-operator-reference#line1686

**Comment by aleskandro** [comment]
This has been completed already. 

/close
