### ISSUE TITLE
Builds of MMO on arm64 MacOS fail

### ISSUE THREAD

**Issue by aleskandro** [outrigger-project/multiarch-tuning-operator#26]
@lwan-wanglin noticed there might be some issue with building the operator image on top of an arm64 MacOS system with `make docker-buildx` and `make docker-build`.

This might be related to https://github.com/golang/go/issues/57485

**Comment by Prashanth684** [comment]
is this operator going to be made available for macos or only linux? that said, we should also think about windows in that case as well

**Comment by aleskandro** [comment]
Yeah, the issue here is about building it 'locally' (e.g., for dev purposes) from a MacOS workstation. We all use Fedora when developing it, but the linked issue might affect builds on MacOS systems based on arm64. We'd try on Windows systems too, if we have any.
