### ISSUE TITLE
Add the kubernetes.io/os selector too

### ISSUE THREAD

**Issue by aleskandro** [outrigger-project/multiarch-tuning-operator#46]
In the future, it might be good for us to include the OS matchExpression too.
it is a good piece of information that is also worth considering for the scheduler predicates. 

For example, windows container images shouldn't "risk" landing into a linux node.

The current official recommendation (for OCP) is to leverage runtime classes that instruct the scheduler as a kind of 'side-effect'/additional feature, so it's just a "possible" future thing that we can onboard for free to consider better the platform information in the manifest list images we inspect

xref https://github.com/openshift/multiarch-manager-operator/pull/44#discussion_r1499492594

**Comment by Prashanth684** [comment]
As we do more additions like this, we should start thinking when we want to expose our features with opt-in flags or options in the CR rather than doing it implicitly under the covers, like something along the lines of:

```
affinitySelector:
     - architecture
     - osType
     - custom
````
